import { useEffect, useMemo, useRef, useState } from "react";
import { Bell, FileText, Shield, Inbox, AlertTriangle, CheckCheck } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { collection, query, where, onSnapshot } from "firebase/firestore";
import { db } from "../../lib/firebase";
import { useAuth } from "../../lib/AuthContext";
import { useIsMobile } from "../../hooks/use-mobile";

// NotificationsBell aggregates the principal's most recent actionable
// activity (reports published + discipline incidents) into a dropdown.
// Red dot shows ONLY when there are unread items — earlier the bell
// had a hardcoded red dot (memory: bug_pattern_fabricated_fallback)
// AND no onClick handler at all.
//
// "Unread" is computed against a localStorage-persisted lastSeenAt
// timestamp (per-principal). Click "Mark all read" → updates timestamp
// → red dot clears.

type FeedKind = "report" | "discipline";
interface FeedItem {
  id: string;
  kind: FeedKind;
  title: string;
  subtitle: string;
  ts: number;
  href: string;
}

const LS_LAST_SEEN_KEY_PREFIX = "principal_notifications_last_seen:";

const NotificationsBell = () => {
  const { userData } = useAuth();
  const navigate = useNavigate();
  const isMobile = useIsMobile();
  const [open, setOpen] = useState(false);
  const [reports, setReports] = useState<FeedItem[]>([]);
  const [incidents, setIncidents] = useState<FeedItem[]>([]);
  const popRef = useRef<HTMLDivElement>(null);
  const btnRef = useRef<HTMLButtonElement>(null);

  // Per-principal lastSeenAt — key includes user id so multi-user
  // browsers don't share read state.
  const lsKey = userData?.id ? LS_LAST_SEEN_KEY_PREFIX + userData.id : "";
  const [lastSeenAt, setLastSeenAt] = useState<number>(() => {
    if (typeof window === "undefined" || !lsKey) return 0;
    const v = window.localStorage.getItem(lsKey);
    return v ? Number(v) || 0 : 0;
  });
  useEffect(() => {
    if (!lsKey) return;
    const v = window.localStorage.getItem(lsKey);
    setLastSeenAt(v ? Number(v) || 0 : 0);
  }, [lsKey]);

  // ─── Listen to recent reports + discipline (branch-scoped, in-memory) ───
  // schoolId-only at server; branchId in-memory (memory:
  // bug_pattern_branch_filter_on_event_streams + branchid_inference_lag).
  useEffect(() => {
    if (!userData?.schoolId) return;
    const branchId = userData.branchId as string | undefined;
    const inBranch = (raw: any) => !branchId || !raw?.branchId || raw.branchId === branchId;

    // schoolId-only at server, sort in-memory — matches the rest of the
    // dashboard (compound where+orderBy queries require composite indexes
    // we don't maintain). Limit to 10 most recent.
    const qReports = query(
      collection(db, "principal_reports"),
      where("schoolId", "==", userData.schoolId),
    );
    const unsubR = onSnapshot(qReports, snap => {
      const rows: FeedItem[] = [];
      snap.docs.forEach(d => {
        const data: any = d.data();
        if (!inBranch(data)) return;
        const ts = data.createdAt?.toMillis?.() || 0;
        rows.push({
          id: d.id,
          kind: "report",
          title: data.title || "New report",
          subtitle: `Generated by ${data.generatedBy || "Principal"}`,
          ts,
          href: "/reports",
        });
      });
      rows.sort((a, b) => b.ts - a.ts);
      setReports(rows.slice(0, 10));
    }, () => { /* silent */ });

    const qDisc = query(
      collection(db, "discipline"),
      where("schoolId", "==", userData.schoolId),
    );
    const unsubD = onSnapshot(qDisc, snap => {
      const rows: FeedItem[] = [];
      snap.docs.forEach(d => {
        const data: any = d.data();
        if (!inBranch(data)) return;
        const tsRaw = data.timestamp || data.createdAt || data.date;
        const ts = tsRaw?.toMillis?.() ||
          (typeof tsRaw === "string" ? Date.parse(tsRaw) || 0 : 0);
        rows.push({
          id: d.id,
          kind: "discipline",
          title: data.studentName || data.student || "Discipline incident",
          subtitle: String(data.type || data.category || data.reason || "Incident logged"),
          ts,
          href: "/discipline",
        });
      });
      // Keep most recent 10 by ts.
      rows.sort((a, b) => b.ts - a.ts);
      setIncidents(rows.slice(0, 10));
    }, () => { /* silent */ });

    return () => { unsubR(); unsubD(); };
  }, [userData?.schoolId, userData?.branchId]);

  // ─── Merge + sort + count unread ───
  const feed = useMemo<FeedItem[]>(() => {
    return [...reports, ...incidents]
      .filter(x => x.ts > 0)
      .sort((a, b) => b.ts - a.ts)
      .slice(0, 12);
  }, [reports, incidents]);

  const unreadCount = useMemo(
    () => feed.filter(item => item.ts > lastSeenAt).length,
    [feed, lastSeenAt],
  );

  // ─── Outside-click + Esc close ───
  useEffect(() => {
    if (!open) return;
    const onDoc = (e: MouseEvent) => {
      if (!popRef.current || !btnRef.current) return;
      if (popRef.current.contains(e.target as Node)) return;
      if (btnRef.current.contains(e.target as Node)) return;
      setOpen(false);
    };
    const onEsc = (e: KeyboardEvent) => { if (e.key === "Escape") setOpen(false); };
    document.addEventListener("mousedown", onDoc);
    document.addEventListener("keydown", onEsc);
    return () => {
      document.removeEventListener("mousedown", onDoc);
      document.removeEventListener("keydown", onEsc);
    };
  }, [open]);

  const markAllRead = () => {
    if (!lsKey) return;
    const now = Date.now();
    window.localStorage.setItem(lsKey, String(now));
    setLastSeenAt(now);
  };

  const onItemClick = (item: FeedItem) => {
    setOpen(false);
    // Mark read on click — anything older than the latest item is now seen.
    if (lsKey && item.ts > lastSeenAt) {
      window.localStorage.setItem(lsKey, String(Date.now()));
      setLastSeenAt(Date.now());
    }
    navigate(item.href);
  };

  const fmtTime = (ts: number) => {
    if (!ts) return "—";
    const diff = Date.now() - ts;
    if (diff < 60_000) return "just now";
    if (diff < 3_600_000) return `${Math.floor(diff / 60_000)}m ago`;
    if (diff < 86_400_000) return `${Math.floor(diff / 3_600_000)}h ago`;
    if (diff < 604_800_000) return `${Math.floor(diff / 86_400_000)}d ago`;
    return new Date(ts).toLocaleDateString("en-IN", { day: "numeric", month: "short" });
  };

  return (
    <div className="relative">
      <button
        ref={btnRef}
        type="button"
        onClick={() => setOpen(o => !o)}
        className="relative p-2 rounded-full hover:bg-secondary transition-colors"
        aria-label={`Notifications (${unreadCount} unread)`}>
        <Bell className="w-5 h-5 text-muted-foreground" />
        {unreadCount > 0 && (
          <span
            className="absolute top-0.5 right-0.5 min-w-[16px] h-[16px] px-1 bg-destructive text-white rounded-full text-[9px] font-bold flex items-center justify-center"
            style={{ boxShadow: "0 1px 4px rgba(255,51,85,0.5)" }}>
            {unreadCount > 9 ? "9+" : unreadCount}
          </span>
        )}
      </button>

      {open && (
        <div
          ref={popRef}
          /* Desktop: anchored absolute right of bell.
             Mobile: position fixed with viewport-relative 8px gutters so the
             dropdown can't overflow past the left edge into the off-canvas
             drawer area. The previous `absolute right-0 w-[360px]
             max-w-[92vw]` extended ~92vw leftward from the bell's right
             edge → on narrow screens the left edge clipped under the side
             drawer. Fixed-with-gutters keeps it visually contained. */
          className={
            isMobile
              ? "fixed left-2 right-2 top-[64px] rounded-[18px] bg-white overflow-hidden z-[60] animate-in fade-in slide-in-from-top-2 duration-150"
              : "absolute right-0 mt-2 w-[360px] max-w-[92vw] rounded-[18px] bg-white overflow-hidden z-[60] animate-in fade-in slide-in-from-top-2 duration-150"
          }
          style={{
            boxShadow: "0 0 0 0.5px rgba(0,85,255,0.10), 0 8px 28px rgba(0,8,60,0.18), 0 24px 56px rgba(0,8,60,0.20)",
            border: "0.5px solid rgba(0,85,255,0.10)",
          }}>
          {/* Header */}
          <div className="flex items-center justify-between px-4 py-[13px]"
            style={{ borderBottom: "0.5px solid rgba(0,85,255,0.10)" }}>
            <div className="flex items-center gap-[8px]">
              <div className="w-7 h-7 rounded-[9px] flex items-center justify-center"
                style={{ background: "linear-gradient(135deg, #0055FF, #1166FF)", boxShadow: "0 3px 10px rgba(0,85,255,0.32)" }}>
                <Bell className="w-[14px] h-[14px] text-white" strokeWidth={2.4} />
              </div>
              <div>
                <div className="text-[13px] font-bold" style={{ color: "#001040", letterSpacing: "-0.2px" }}>Notifications</div>
                <div className="text-[10px] font-medium" style={{ color: "#5070B0" }}>
                  {unreadCount > 0
                    ? `${unreadCount} unread`
                    : feed.length === 0 ? "All clear" : "All caught up"}
                </div>
              </div>
            </div>
            <div className="flex items-center gap-2">
              {unreadCount > 0 && (
                <button
                  onClick={markAllRead}
                  className="flex items-center gap-1 text-[11px] font-bold px-[10px] py-[5px] rounded-full transition-transform hover:scale-[1.04]"
                  style={{ background: "rgba(0,85,255,0.10)", color: "#0055FF", border: "0.5px solid rgba(0,85,255,0.20)" }}>
                  <CheckCheck className="w-[12px] h-[12px]" strokeWidth={2.4} />
                  Mark all read
                </button>
              )}
              <button
                type="button"
                onClick={() => setOpen(false)}
                aria-label="Close notifications"
                style={{
                  width: 28,
                  height: 28,
                  borderRadius: "9999px",
                  background: "rgba(0,85,255,0.08)",
                  color: "#001040",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  fontSize: 20,
                  fontWeight: 900,
                  lineHeight: 1,
                  border: "0.5px solid rgba(0,85,255,0.15)",
                  cursor: "pointer",
                  fontFamily: "Arial, sans-serif",
                  paddingBottom: 3,
                  transition: "background-color 150ms",
                }}
              >
                ×
              </button>
            </div>
          </div>

          {/* Feed */}
          <div className="max-h-[60vh] overflow-y-auto">
            {feed.length === 0 ? (
              <div className="py-10 px-4 flex flex-col items-center gap-2 text-center">
                <div className="w-12 h-12 rounded-[14px] flex items-center justify-center"
                  style={{ background: "linear-gradient(135deg,#E5EEFF,#D4E4FF)", border: "0.5px solid rgba(0,85,255,0.18)" }}>
                  <Inbox className="w-5 h-5" style={{ color: "#0055FF" }} strokeWidth={2.2} />
                </div>
                <div className="text-[12px] font-bold" style={{ color: "#001040" }}>You're all caught up</div>
                <div className="text-[10px]" style={{ color: "#99AACC" }}>
                  New reports and incidents will appear here.
                </div>
              </div>
            ) : (
              feed.map(item => {
                const unread = item.ts > lastSeenAt;
                const Icon = item.kind === "report" ? FileText
                  : item.kind === "discipline" ? Shield
                  : AlertTriangle;
                const iconBg = item.kind === "report"
                  ? "rgba(0,85,255,0.10)"
                  : "rgba(255,51,85,0.10)";
                const iconColor = item.kind === "report" ? "#0055FF" : "#FF3355";
                return (
                  <button
                    key={`${item.kind}:${item.id}`}
                    type="button"
                    onClick={() => onItemClick(item)}
                    className="w-full text-left flex items-start gap-[11px] px-4 py-[11px] hover:bg-[#F5F8FF] transition-colors"
                    style={{ borderBottom: "0.5px solid rgba(0,85,255,0.06)" }}>
                    <div className="w-9 h-9 rounded-[11px] flex items-center justify-center shrink-0"
                      style={{ background: iconBg, border: `0.5px solid ${iconColor}33` }}>
                      <Icon className="w-[16px] h-[16px]" style={{ color: iconColor }} strokeWidth={2.3} />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-start justify-between gap-2">
                        <div className="text-[12px] font-bold truncate" style={{ color: "#001040" }}>
                          {item.title}
                        </div>
                        {unread && (
                          <div className="w-[7px] h-[7px] rounded-full mt-[5px] shrink-0"
                            style={{ background: "#FF3355", boxShadow: "0 0 6px rgba(255,51,85,0.6)" }} />
                        )}
                      </div>
                      <div className="text-[10px] font-medium mt-[1px] truncate" style={{ color: "#5070B0" }}>
                        {item.subtitle}
                      </div>
                      <div className="text-[9px] font-bold uppercase tracking-[0.06em] mt-[3px]" style={{ color: "#99AACC" }}>
                        {fmtTime(item.ts)}
                      </div>
                    </div>
                  </button>
                );
              })
            )}
          </div>
        </div>
      )}
    </div>
  );
};

export default NotificationsBell;
